apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: utsav
  name: &name utsav
  namespace: &namespace utsav-rnd
spec:
  replicas: 3
  selector:
    matchLabels:
      service: http-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: http-server
    spec:
      containers:
      - name: &name nginx
        image: &image nginx:1.10.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80


